# Generated by Django 5.2.7 on 2025-10-14 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='is_deleted',
        ),
    ]
